title: Osama Kamal
logo: /assets /img/osama-headshot.png
description: Data Analytics Portfolio
show_downloads: false
github:
  is_project_page: false
theme: jekyll-theme-minimal
defaults:
  -
    scope:
      path: ""
    values:
      full-width: true

